# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 */3 * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: dippyshere
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Australia/Sydney
          optimize: true
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_limit: 4
          plugin_activity_load: 100
          plugin_activity_visibility: all
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: lenovo-s6000-osc, BetterDiscordPlugins
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 60
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: json
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base
          plugin_lines_skipped: lenovo-s6000-osc, BetterDiscordPlugins
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 300
          plugin_habits_languages_limit: 10
          plugin_habits_languages_threshold: 0%
          plugin_habits_skipped: lenovo-s6000-osc, BetterDiscordPlugins
          plugin_habits_trim: true
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 24
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_display: relative
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
