# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 */3 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dippyshere
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          repositories_affiliations: owner, collaborator
          repositories_skipped: |
            @use.patterns
            dippyshere/lenovo-s6000-osc
            dippyshere/BetterDiscordPlugins
            dippyshere/uYouEnhanced
            EpicGames/*
            IJWTD-Studios/*
            Blind-Chihuahua/*
            Reflective-Glass-Border/*
            fxesdev/*
          plugin_achievements: no
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_limit: 4
          plugin_activity_load: 100
          plugin_activity_visibility: public
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 60
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: json
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base
          plugin_habits: yes
          plugin_habits_charts: no
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: no
          plugin_habits_languages_limit: 10
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: true
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 24
          plugin_people_types: followers, following
          plugin_reactions: no
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
